on: 
    push:
        branches: [main, master, workflow_testing]


jobs:
  production_job:
    runs-on: ubuntu-latest
    name: set up project 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: read-yaml-file
        uses: pietrobolcato/action-read-yaml@1.0.0
        id: read_action_js
        with:
            config: ${{ github.workspace }}/project_settings.yaml

      - name: Setting up Python and chevron to processes reports
        # workflows really need some more work done on them
        if: ${{ !cancelled() && steps.read_action_js.outputs.has_been_set_up}} 
        uses: actions/setup-python@v5 
        with:
            python-version: '3.10'
            cache: 'pip'
        
      - name: installing requirements  
        if: ${{ !cancelled() && steps.read_action_js.outputs.has_been_set_up}} 
        run: pip install -r ${{ github.workspace }}/.github/report_processing/requirements.txt

      - name: Run KiCad ERC
        id: erc
        uses: sparkengineering/kicad-action@v3
        if: '!cancelled()'
        with:
          kicad_sch: Hardware/${{steps.read_action_js.outputs.project_name}}_PROJECT/${{steps.read_action_js.outputs.project_name}}.kicad_sch
          sch_erc: true
          report_format: json
          sch_erc_file: erc.json
      
      - name: move ERC report
        if: '!cancelled()'
        run:
              mv ${{ github.workspace }}/Hardware/${{steps.read_action_js.outputs.project_name}}_PROJECT/erc.json ${{ github.workspace }}/Hardware/${{steps.read_action_js.outputs.project_name}}_DOCS/reports/erc.json
  
      - name: creating ERC report in markdown
        if: ${{ !cancelled() }} 
        run: python ${{ github.workspace }}/.github/report_processing/process_json_reports.py ${{ github.workspace }}/Hardware/${{steps.read_action_js.outputs.project_name}}_DOCS/reports/erc.json ${{ github.workspace }}/${{steps.read_action_js.outputs.erc_report_template_path}} ${{ github.workspace }}/Hardware/${{steps.read_action_js.outputs.project_name}}_DOCS/reports/erc.md
    
      - name: commit production files
        if: ${{ !cancelled() && steps.read_action_js.outputs.has_been_set_up}} 
        uses: EndBug/add-and-commit@v9
        with:
            default_author: github_actions
            message: 'production files'
            push: true
            tag_push: '--force' # just makes life easier
            add: "."