
name: "KiCAD DRC/ERC"


on: push


jobs:
  
  kicad_drc:

    runs-on: ubuntu-latest
    name: "KiCAD DRC"

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: KiCAD Setup
        id: kicad_setup
        uses: ./.github/workflows/kicad_setup.yaml

      - name: Run KiCAD DRC
        id: drc
        uses: sparkengineering/kicad-action@v3
        if: '!cancelled()'
        with:
          kicad_pcb: Hardware/${{steps.kicad_setup.outputs.settings.project_name}}_PROJECT/${{steps.kicad_setup.outputs.settings.project_name}}.kicad_pcb
          pcb_drc: true
          report_format: json
          pcb_drc_file: drc.json

      - name: Move JSON DRC report
        if: '!cancelled()'
        run:
          mv ${{ github.workspace }}/Hardware/${{steps.kicad_setup.outputs.settings.project_name}}_PROJECT/drc.json ${{ github.workspace }}/Hardware/${{steps.kicad_setup.outputs.settings.project_name}}_DOCS/reports/drc.json

      - name: Create markdown DRC report
        if: ${{ !cancelled() }} 
        run: python ${{ github.workspace }}/.github/report_processing/process_json_reports.py ${{ github.workspace }}/Hardware/${{steps.kicad_setup.outputs.settings.project_name}}_DOCS/reports/drc.json ${{ github.workspace }}/${{steps.kicad_setup.outputs.settings.drc_report_template_path}} ${{ github.workspace }}/Hardware/${{steps.kicad_setup.outputs.settings.project_name}}_DOCS/reports/drc.md
  

  kicad_erc:

    runs-on: ubuntu-latest
    name: "KiCAD ERC"

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: KiCAD Setup
        id: kicad_setup
        uses: ./.github/workflows/kicad_setup.yaml

      - name: Run KiCAD ERC
        id: erc
        uses: sparkengineering/kicad-action@v3
        if: '!cancelled()'
        with:
          kicad_sch: Hardware/${{steps.kicad_setup.outputs.settings.project_name}}_PROJECT/${{steps.kicad_setup.outputs.settings.project_name}}.kicad_sch
          sch_erc: true
          report_format: json
          sch_erc_file: erc.json

      - name: Move JSON ERC report
        if: '!cancelled()'
        run:
            mv ${{ github.workspace }}/Hardware/${{steps.kicad_setup.outputs.settings.project_name}}_PROJECT/erc.json ${{ github.workspace }}/Hardware/${{steps.kicad_setup.outputs.settings.project_name}}_DOCS/reports/erc.json

      - name: Create markdown ERC report
        if: ${{ !cancelled() }} 
        run: python ${{ github.workspace }}/.github/report_processing/process_json_reports.py ${{ github.workspace }}/Hardware/${{steps.kicad_setup.outputs.settings.project_name}}_DOCS/reports/erc.json ${{ github.workspace }}/${{steps.kicad_setup.outputs.settings.erc_report_template_path}} ${{ github.workspace }}/Hardware/${{steps.kicad_setup.outputs.settings.project_name}}_DOCS/reports/erc.md


  kicad_push_reports:

    runs-on: ubuntu-latest
    name: "KiCAD push DRC/ERC reports"

    needs: [kicad_drc, kicad_erc]

    steps:
    
      - name: Push DRC/ERC reports
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Update DRC/ERC reports"
          push: true
          add: "."
  
