on: push

jobs:
  kicad_job:
    runs-on: ubuntu-latest
    name: Kicad job
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Export production files
        id: production
        uses: sparkengineering/kicad-action@v3
        if: '!cancelled()'
        with:
          kicad_sch: Hardware/template/template.kicad_sch
          sch_pdf: true # Generate PDF
          sch_bom: true # Generate BOM
          kicad_pcb: Hardware/template/template.kicad_pcb
          pcb_gerbers: true # Generate Gerbers
            
      # Upload production files only if generation succeeded
      - name: Upload production files
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() && steps.production.conclusion == 'success' }}
        with:
          name: Production files
          path: |
            ${{ github.workspace }}/Hardware/template/sch.pdf
            ${{ github.workspace }}/bom.csv
            ${{ github.workspace }}/gbr.zip

      - name: Moving production files to correct location
        if: ${{ !cancelled() && steps.production.conclusion == 'success' }}
        run: |  
            mv ${{ github.workspace }}/Hardware/template/sch.pdf ${{ github.workspace }}/Hardware_Docs/sch.pdf
            mv ${{ github.workspace }}/Hardware/template/bom.csv ${{ github.workspace }}/Hardware_Docs/BOM/bom.csv
            mv ${{ github.workspace }}/Hardware/template/gbr.zip ${{ github.workspace }}/Hardware/template_PCB/gbr.zip

      - name: commit production files
        if: ${{ !cancelled() && steps.production.conclusion == 'success' }}
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Your commit message'
          push: true
          add: |
            ${{ github.workspace }}/Hardware_Docs/sch.pdf
            ${{ github.workspace }}/Hardware_Docs/BOM/bom.csv
            ${{ github.workspace }}/Hardware/template_PCB/gbr.zip

      - name: Run KiCad ERC
        id: erc
        uses: sparkengineering/kicad-action@v3
        if: '!cancelled()'
        with:
          kicad_sch: Hardware/template/template.kicad_sch
          sch_erc: true

      - name: Run KiCad DRC
        id: drc
        uses: sparkengineering/kicad-action@v3
        if: '!cancelled()'
        with:
          kicad_pcb: Hardware/template/template.kicad_pcb
          pcb_drc: true

      # Upload ERC report only if ERC failed
      - name: Upload ERC report
        uses: actions/upload-artifact@v4
        if: ${{ failure() && steps.erc.conclusion == 'failure' }}
        with:
          name: erc.rpt
          path: ${{ github.workspace }}/erc.rpt

      # Upload DRC report only if DRC failed
      - name: Upload DRC report
        uses: actions/upload-artifact@v4
        if: ${{ failure() && steps.drc.conclusion == 'failure' }}
        with:
          name: drc.rpt
          path: ${{ github.workspace }}/drc.rpt