on: 
    push:
        branches: [main, master, workflow_testing]

jobs:
  kicad_job:
    runs-on: ubuntu-latest
    name: creating BOM schematic pdf and grbrs 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Export production files
        id: production
        uses: sparkengineering/kicad-action@v3
        if: '!cancelled()'
        with:
          kicad_sch: Hardware/template_PROJECT/template.kicad_sch
          sch_pdf: true # Generate PDF
          sch_bom: true # Generate BOM
          kicad_pcb: Hardware/template_PROJECT/template.kicad_pcb
          pcb_gerbers: true # Generate Gerbers

      - name: Moving production files to correct location
        if: ${{ !cancelled() && steps.production.conclusion == 'success' }}
        run: |  
            mv ${{ github.workspace }}/Hardware/template_PROJECT/sch.pdf ${{ github.workspace }}/Hardware/template_DOCS/template_schematic.pdf
            mv ${{ github.workspace }}/Hardware/template_PROJECT/bom.csv ${{ github.workspace }}/Hardware/template_DOCS/BOM/bill_of_materials.csv
            mv ${{ github.workspace }}/Hardware/template_PROJECT/gbr.zip ${{ github.workspace }}/Hardware/template_PCB/grbr.zip

      - name: commit production files
        if: ${{ !cancelled() && steps.production.conclusion == 'success' }}
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'auto updated doc'
          push: true
          add: |
            ${{ github.workspace }}/Hardware/template_DOCS/template_schematic.pdf
            ${{ github.workspace }}/Hardware/template_DOCS/BOM/bill_of_materials.csv
            ${{ github.workspace }}/Hardware/template_PCB/grbr.zip

  # on fail it should upload the json as well
  rules_check_check:
    runs-on: ubuntu-latest
    name: drc reports
    needs: kicad_job
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: adding rules check reports
        uses: EndBug/add-and-commit@v9
        with:
          push: false
          pull: "--rebase"
  
      - name: Run KiCad DRC
        id: drc
        uses: sparkengineering/kicad-action@v3
        if: '!cancelled()'
        with:
          kicad_pcb: Hardware/template_PROJECT/template.kicad_pcb
          pcb_drc: true
          report_format: json
          pcb_drc_file: drc.json

      - name: Run KiCad ERC
        id: erc
        uses: sparkengineering/kicad-action@v3
        if: '!cancelled()'
        with:
          kicad_sch: Hardware/template_PROJECT/template.kicad_sch
          sch_erc: true
          report_format: json
          sch_erc_file: erc.json

      - name: move DRC report
        if: '!cancelled()'
        run:
          mv ${{ github.workspace }}/Hardware/template_PROJECT/drc.json ${{ github.workspace }}/Hardware/template_DOCS/reports/drc.json

      - name: move ERC report
        if: '!cancelled()'
        run:
            mv ${{ github.workspace }}/Hardware/template_PROJECT/erc.json ${{ github.workspace }}/Hardware/template_DOCS/reports/erc.json

      - name: Setting up Python and chevron to processes failed reports
        uses: actions/setup-python@v5 
        with:
            python-version: '3.10'
            cache: 'pip'
          # if this doesnt work i will just install chevron itself
      - name: installing requirements  
        run: pip install -r ${{ github.workspace }}/.github/requirements.txt

      - name: creating ERC report in markdown
        if: ${{ steps.erc.conclusion == 'failure' && !cancelled() }} 
        run: python ${{ github.workspace }}/.github/report_processing/process_json_files.py ${{ github.workspace }}/Hardware/template_DOCS/reports/erc.json ${{ github.workspace }}/.github/report_templates/erc_report_template.mustache ${{ github.workspace }}/Hardware/template_DOCS/reports/erc.md
      
      - name: creating DRC report in markdown
        if: ${{ steps.drc.conclusion == 'failure' && !cancelled() }} 
        run: python ${{ github.workspace }}/.github/report_processing/process_json_files.py ${{ github.workspace }}/Hardware/template_DOCS/reports/drc.json ${{ github.workspace }}/.github/report_templates/drc_report_template.mustache ${{ github.workspace }}/Hardware/template_DOCS/reports/drc.md
  
      - name: adding rules check reports
        if: ${{ steps.erc.conclusion == 'failure' || steps.drc.conclusion == 'failure' && !cancelled() }}
        uses: EndBug/add-and-commit@v9
        with:
            default_author: github_actions
            message: 'failed RC report/s'
            push: true