on: 
    push:
        branches: [main, master, workflow_testing]

jobs:
  setup_job:
    runs-on: ubuntu-latest
    name: set up project 
    if : ${{ github.repository != 'sirlilpanda/kicad-project-template' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: read-yaml-file
        uses: pietrobolcato/action-read-yaml@1.0.0
        id: read_action_js
        with:
          config: ${{ github.workspace }}/project_settings.yaml

      - name: Setting up Python and chevron to processes failed reports
        # workflows really need some more work done on them
        if: ${{ !cancelled() && steps.read_action_js.outputs.has_been_set_up}} 
        uses: actions/setup-python@v5 
        with:
            python-version: '3.10'
            cache: 'pip'
      
      - name: installing requirements  
        if: ${{ !cancelled() && steps.read_action_js.outputs.has_been_set_up}} 
        run: pip install -r ${{ github.workspace }}/.github/report_processing/requirements.txt
      
      - name: rename project if setup has not been completed
        if: ${{ !cancelled() && steps.read_action_js.outputs.has_been_set_up}} 
        run: python ${{ github.workspace }}/.github/rename.py ${{github.event.repository.name}} 

      - name: commit production files
        if: ${{ !cancelled() && steps.read_action_js.outputs.has_been_set_up}} 
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'setup project'
          push: true
          add: "."

  DRC:
    runs-on: ubuntu-latest
    name: set up project 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: read-yaml-file
        uses: pietrobolcato/action-read-yaml@1.0.0
        id: read_action_js
        with:
            config: ${{ github.workspace }}/project_settings.yaml

      - name: Setting up Python and chevron to processes reports
        # workflows really need some more work done on them
        if: ${{ !cancelled() && steps.read_action_js.outputs.has_been_set_up}} 
        uses: actions/setup-python@v5 
        with:
            python-version: '3.10'
            cache: 'pip'
        
      - name: installing requirements  
        if: ${{ !cancelled() && steps.read_action_js.outputs.has_been_set_up}} 
        run: pip install -r ${{ github.workspace }}/.github/report_processing/requirements.txt

      - name: Run KiCad DRC
        id: drc
        uses: sparkengineering/kicad-action@v3
        if: '!cancelled()'
        with:
          kicad_pcb: Hardware/${{steps.read_action_js.outputs.project_name}}_PROJECT/${{steps.read_action_js.outputs.project_name}}.kicad_pcb
          pcb_drc: true
          report_format: json
          pcb_drc_file: drc.json
      
      
      - name: move DRC report
        if: '!cancelled()'
        run:
            mv ${{ github.workspace }}/Hardware/${{steps.read_action_js.outputs.project_name}}_PROJECT/drc.json ${{ github.workspace }}/Hardware/${{steps.read_action_js.outputs.project_name}}_DOCS/reports/drc.json
      
      - name: creating DRC report in markdown
        if: ${{ !cancelled() }} 
        run: python ${{ github.workspace }}/.github/report_processing/process_json_reports.py ${{ github.workspace }}/Hardware/${{steps.read_action_js.outputs.project_name}}_DOCS/reports/drc.json ${{ github.workspace }}/${{steps.read_action_js.outputs.drc_report_template_path}} ${{ github.workspace }}/Hardware/${{steps.read_action_js.outputs.project_name}}_DOCS/reports/drc.md
      
      - name: upload report
        uses: actions/upload-artifact@v4
        with: 
          name: drc-report
          path: ${{ github.workspace }}/Hardware/${{steps.read_action_js.outputs.project_name}}_DOCS/reports/drc.md

  ERC:
    runs-on: ubuntu-latest
    name: set up project 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: read-yaml-file
        uses: pietrobolcato/action-read-yaml@1.0.0
        id: read_action_js
        with:
            config: ${{ github.workspace }}/project_settings.yaml

      - name: Setting up Python and chevron to processes reports
        # workflows really need some more work done on them
        if: ${{ !cancelled() && steps.read_action_js.outputs.has_been_set_up}} 
        uses: actions/setup-python@v5 
        with:
            python-version: '3.10'
            cache: 'pip'
        
      - name: installing requirements  
        if: ${{ !cancelled() && steps.read_action_js.outputs.has_been_set_up}} 
        run: pip install -r ${{ github.workspace }}/.github/report_processing/requirements.txt

      - name: Run KiCad ERC
        id: erc
        uses: sparkengineering/kicad-action@v3
        if: '!cancelled()'
        with:
          kicad_sch: Hardware/${{steps.read_action_js.outputs.project_name}}_PROJECT/${{steps.read_action_js.outputs.project_name}}.kicad_sch
          sch_erc: true
          report_format: json
          sch_erc_file: erc.json
      
      - name: move ERC report
        if: '!cancelled()'
        run:
              mv ${{ github.workspace }}/Hardware/${{steps.read_action_js.outputs.project_name}}_PROJECT/erc.json ${{ github.workspace }}/Hardware/${{steps.read_action_js.outputs.project_name}}_DOCS/reports/erc.json
  
      - name: creating ERC report in markdown
        if: ${{ !cancelled() }} 
        run: python ${{ github.workspace }}/.github/report_processing/process_json_reports.py ${{ github.workspace }}/Hardware/${{steps.read_action_js.outputs.project_name}}_DOCS/reports/erc.json ${{ github.workspace }}/${{steps.read_action_js.outputs.erc_report_template_path}} ${{ github.workspace }}/Hardware/${{steps.read_action_js.outputs.project_name}}_DOCS/reports/erc.md
    
      - name: upload report
        uses: actions/upload-artifact@v4
        with: 
          name: erc-report
          path: ${{ github.workspace }}/Hardware/${{steps.read_action_js.outputs.project_name}}_DOCS/reports/erc.md


  production_job:
    runs-on: ubuntu-latest
    name: set up project 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: read-yaml-file
        uses: pietrobolcato/action-read-yaml@1.0.0
        id: read_action_js
        with:
            config: ${{ github.workspace }}/project_settings.yaml

      - name: Setting up Python and chevron to processes reports
        # workflows really need some more work done on them
        if: ${{ !cancelled() && steps.read_action_js.outputs.has_been_set_up}} 
        uses: actions/setup-python@v5 
        with:
            python-version: '3.10'
            cache: 'pip'
        
      - name: installing requirements  
        if: ${{ !cancelled() && steps.read_action_js.outputs.has_been_set_up}} 
        run: pip install -r ${{ github.workspace }}/.github/report_processing/requirements.txt

      - name: Export production files
        id: production
        uses: sparkengineering/kicad-action@v3
        if: '!cancelled()'
        with:
          kicad_sch: Hardware/${{steps.read_action_js.outputs.project_name}}_PROJECT/${{steps.read_action_js.outputs.project_name}}.kicad_sch
          sch_pdf: true # Generate PDF
          sch_bom: true # Generate BOM
          kicad_pcb: Hardware/${{steps.read_action_js.outputs.project_name}}_PROJECT/${{steps.read_action_js.outputs.project_name}}.kicad_pcb
          pcb_gerbers: true # Generate Gerbers

      - name: Moving production files to correct location
        if: ${{ !cancelled() && steps.production.conclusion == 'success' }}
        run: |  
            mv ${{ github.workspace }}/Hardware/${{steps.read_action_js.outputs.project_name}}_PROJECT/sch.pdf ${{ github.workspace }}/Hardware/${{steps.read_action_js.outputs.project_name}}_DOCS/${{steps.read_action_js.outputs.project_name}}_schematic.pdf
            mv ${{ github.workspace }}/Hardware/${{steps.read_action_js.outputs.project_name}}_PROJECT/bom.csv ${{ github.workspace }}/Hardware/${{steps.read_action_js.outputs.project_name}}_DOCS/BOM/bill_of_materials.csv
            mv ${{ github.workspace }}/Hardware/${{steps.read_action_js.outputs.project_name}}_PROJECT/gbr.zip ${{ github.workspace }}/Hardware/${{steps.read_action_js.outputs.project_name}}_PCB/grbr.zip


      - name: upload report
        uses: actions/upload-artifact@v4
        with: 
          name: production-files
          path: |
            ${{ github.workspace }}/Hardware/${{steps.read_action_js.outputs.project_name}}_DOCS/${{steps.read_action_js.outputs.project_name}}_schematic.pdf
            ${{ github.workspace }}/Hardware/${{steps.read_action_js.outputs.project_name}}_DOCS/BOM/bill_of_materials.csv
            ${{ github.workspace }}/Hardware/${{steps.read_action_js.outputs.project_name}}_PCB/grbr.zip
    
  
  upload_job:
    runs-on: ubuntu-latest
    name: commit production files
    if: ${{ always() }}
    needs: [DRC, ERC, production_job]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: read-yaml-file
        uses: pietrobolcato/action-read-yaml@1.0.0
        id: read_action_js
        with:
            config: ${{ github.workspace }}/project_settings.yaml

      - name: download production files
        uses: actions/download-artifact@v4
        with:
          pattern: production-files
          path: ${{ github.workspace }}

      - name: download drc report
        uses: actions/download-artifact@v4
        with:
          pattern: drc-report
          path: ${{ github.workspace }}
          
      - name: download erc report
        uses: actions/download-artifact@v4
        with:
          pattern: erc-report
          path: ${{ github.workspace }}
          
      - name: check downloads
        run: ls -R

      - name: Moving files to correct location
        run: |  
            mv ${{ github.workspace }}/${{steps.read_action_js.outputs.project_name}}_schematic.pdf ${{ github.workspace }}/Hardware/${{steps.read_action_js.outputs.project_name}}_DOCS/${{steps.read_action_js.outputs.project_name}}_schematic.pdf
            mv ${{ github.workspace }}/bill_of_materials.csv ${{ github.workspace }}/Hardware/${{steps.read_action_js.outputs.project_name}}_DOCS/BOM/bill_of_materials.csv
            mv ${{ github.workspace }}/grbr.zip ${{ github.workspace }}/Hardware/${{steps.read_action_js.outputs.project_name}}_PCB/grbr.zip
            mv ${{ github.workspace }}/erc.md ${{ github.workspace }}/Hardware/${{steps.read_action_js.outputs.project_name}}_DOCS/reports/erc.md
            mv ${{ github.workspace }}/drc.md ${{ github.workspace }}/Hardware/${{steps.read_action_js.outputs.project_name}}_DOCS/reports/drc.md

      - name: commit production files
        uses: EndBug/add-and-commit@v9
        with:
            default_author: github_actions
            message: 'production files'
            push: true
            pull: '--rebase --autostash'
            tag_push: '--force' # just makes life easier
            tag: 'v1.0.0 --force'
            add: "."