on: 
    push:
        branches: [main, master, workflow_testing]
jobs:
    setup_job:
        runs-on: ubuntu-latest
        name: setup
        if: github.repository != 'sirlilpanda/kicad-project-template'
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Set up Python
              uses: actions/setup-python@v5 
              with:
                python-version: '3.10'
                
            - name: check if setup has been completed
              if: 'test -f ${{ github.workspace }}/.github/.setup_complete'
              run: |
                python ${{ github.workspace }}/tools.py rename ${{github.event.repository.name}}
                touch ${{ github.workspace }}/.github/.setup_complete
            
            - name: update repo
              uses: EndBug/add-and-commit@v9
              with:
                  default_author: github_actions
                  message: 'setup repo'
                  push: true
                  add: .