name: setup repo
on:   
    repository_dispatch:
        types: [on_scaffold_repo]

jobs:
    setup_job:
        if: github.ref == 'refs/heads/main' && github.event.client_payload.scaffold_type == 'setup'
        runs-on: ubuntu-latest
        name: setup
        steps:
            - name: Checkout
              uses: actions/checkout@v4
        
            - name: Set up Python
              uses: actions/setup-python@v5 
              with:
                python-version: '3.10'
            
            - name: change repo name
              run: python ${{ github.workspace }}/tools.py $${{github.event.repository.name}}
            
            - name: update repo
              uses: EndBug/add-and-commit@v9
              with:
                default_author: github_actions
                message: 'setup repo'
                push: true
                add: .